In [2]:
# Biblioteki wejściowe
import pandas as pd
import numpy as np
import posixpath as os
import pathlib
from pathlib import Path
import pyodbc
import sys
import plotly.express as px
import plotly.io as pio
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from pandas.tseries.offsets import MonthEnd
import IPython

pd.set_option("display.max_rows", None)
#pd.options.display.max_rows=50000
pd.options.display.max_colwidth=70
#pd.options.display.min_colwidth=10
pd.options.display.precision=2
pd.options.display.max_columns=50
pd.options.display.float_format='{0:,.2f}'.format

DATA = Path(r'/Users/daniel_wojcik/Documents/KOPALNIA/FINANSE (RAPORTY)/STRATEGIA 2023-2028/DATA')
ASSETS = Path(r'/Users/daniel_wojcik/Documents/KOPALNIA/FINANSE (RAPORTY)/STRATEGIA 2023-2028/ASSETS')
IMAGES = Path(r'/Users/daniel_wojcik/Documents/KOPALNIA/FINANSE (RAPORTY)/STRATEGIA 2023-2028/IMAGES')

t_zapisy=pd.read_csv(DATA /'SF_Zapisy_RAP.csv')
t_balance=pd.read_csv(DATA /'SF_Balance_RAP.csv')
msc=11

## Raport

In [3]:
# t_mapa_sprawozdania

l_mapa=[['Aktywa','A. Aktywa trwałe', 'I. Wartości niematerialne i prawne', '1. Wartości niematerialne i prawne',
  '1. Wartości niematerialne i prawne',
  'A1'],
 ['Aktywa',
  'A. Aktywa trwałe',
  'II. Rzeczowe aktywa trwałe',
  '2. Środki trwałe',
  'a) Grunty (w tym prawo uw)',
  'A2'],
 ['Aktywa',
  'A. Aktywa trwałe',
  'II. Rzeczowe aktywa trwałe',
  '2. Środki trwałe',
  'b) Budynki, lokale etc.',
  'A3'],
 ['Aktywa',
  'A. Aktywa trwałe',
  'II. Rzeczowe aktywa trwałe',
  '2. Środki trwałe',
  'c) Urządzenia techniczne i maszyny',
  'A4'],
 ['Aktywa',
  'A. Aktywa trwałe',
  'II. Rzeczowe aktywa trwałe',
  '2. Środki trwałe',
  'd) Środki transportu',
  'A5'],
 ['Aktywa',
  'A. Aktywa trwałe',
  'II. Rzeczowe aktywa trwałe',
  '2. Środki trwałe',
  'e) Inne środki trwałe',
  'A6'],
 ['Aktywa',
  'A. Aktywa trwałe',
  'II. Rzeczowe aktywa trwałe',
  '3. Środki trwałe w budowie',
  '3. Środki trwałe w budowie',
  'A7'],
 ['Aktywa',
  'A. Aktywa trwałe',
  'III. Należności długoterminowe',
  'III. Należności długoterminowe',
  'III. Należności długoterminowe',
  'A8'],
 ['Aktywa',
  'A. Aktywa trwałe',
  'IV. Inwestycje długoterminowe',
  '1. Długoterminowe aktywa finansowe',
  '1. Długoterminowe aktywa finansowe',
  'A9'],
 ['Aktywa',
  'A. Aktywa trwałe',
  'V. Długoterminowe rozliczenia międzyokresowe',
  '1. Aktywa z tytułu odroczonego podatku dochodowego',
  '1. Aktywa z tytułu odroczonego podatku dochodowego',
  'A10'],
 ['Aktywa',
  'A. Aktywa trwałe',
  'V. Długoterminowe rozliczenia międzyokresowe',
  '2. Inne rozliczenia międzyokresowe',
  '2. Inne rozliczenia międzyokresowe',
  'A11'],
 ['Aktywa',
  'B. Aktywa obrotowe',
  'I. Zapasy',
  '1. Materiały',
  '1. Materiały',
  'A12'],
 ['Aktywa',
  'B. Aktywa obrotowe',
  'I. Zapasy',
  '2. Produkty gotowe',
  '2. Produkty gotowe',
  'A13'],
 ['Aktywa',
  'B. Aktywa obrotowe',
  'II. Należności krótkoterminowe',
  '1. Należności od jednostek powiązanych',
  'a) z tytułu dostaw i usług',
  'A14'],
 ['Aktywa',
  'B. Aktywa obrotowe',
  'II. Należności krótkoterminowe',
  '2. Należności od pozostałych jednostek',
  'a) z tytułu dostaw i usług',
  'A15'],
 ['Aktywa',
  'B. Aktywa obrotowe',
  'II. Należności krótkoterminowe',
  '2. Należności od pozostałych jednostek',
  'b) z tytułu podatków, dotacji, ceł, etc.',
  'A16'],
 ['Aktywa',
  'B. Aktywa obrotowe',
  'II. Należności krótkoterminowe',
  '2. Należności od pozostałych jednostek',
  'c) inne',
  'A17'],
 ['Aktywa',
  'B. Aktywa obrotowe',
  'III. Inwestycje krótkoterminowe',
  '1. Krótkoterminowe aktywa finansowe',
  'a) środki pieniężne i inne aktywa pieniężne',
  'A18'],
 ['Aktywa',
  'B. Aktywa obrotowe',
  'IV. Krótkoterminowe rozliczenia międzyokresowe',
  '1. Krótkoterminowe rozliczenia międzyokresowe',
  '1. Krótkoterminowe rozliczenia międzyokresowe',
  'A19'],
 ['Pasywa',
  'A. Kapitał (fundusz) własny',
  'I. Kapitał (fundusz) podstawowy',
  'I. Kapitał (fundusz) podstawowy',
  'I. Kapitał (fundusz) podstawowy',
  'P1'],
 ['Pasywa',
  'A. Kapitał (fundusz) własny',
  'II. Kapitał (fundusz) zapasowy',
  'II. Kapitał (fundusz) zapasowy',
  'II. Kapitał (fundusz) zapasowy',
  'P2'],
 ['Pasywa',
  'A. Kapitał (fundusz) własny',
  'III. Kapitał (fundusz) z aktualizacji wyceny',
  'III. Kapitał (fundusz) z aktualizacji wyceny',
  'III. Kapitał (fundusz) z aktualizacji wyceny',
  'P3'],
 ['Pasywa',
  'A. Kapitał (fundusz) własny',
  'IV. Pozostałe kapitały (fundusze) rezerwowe',
  'IV. Pozostałe kapitały (fundusze) rezerwowe',
  'IV. Pozostałe kapitały (fundusze) rezerwowe',
  'P4'],
 ['Pasywa',
  'A. Kapitał (fundusz) własny',
  'V. Zysk (strata) netto',
  'V. Zysk (strata) netto',
  'V. Zysk (strata) netto',
  'P5'],
 ['Pasywa',
  'A. Kapitał (fundusz) własny',
  'VI. Odpisy w ciągu roku obrotowego',
  'VI. Odpisy w ciągu roku obrotowego',
  'VI. Odpisy w ciągu roku obrotowego',
  'P6'],
 ['Pasywa',
  'B. Zobowiązania i rezerwy na zobowiązania',
  'I. Rezerwy na zobowiązania',
  '1. Rezerwa z tytułu odroczonego podatku dochodowego',
  '1. Rezerwa z tytułu odroczonego podatku dochodowego',
  'P7'],
 ['Pasywa',
  'B. Zobowiązania i rezerwy na zobowiązania',
  'I. Rezerwy na zobowiązania',
  '2. Rezerwa na świadczenia emerytalne i podobne',
  '2. Rezerwa na świadczenia emerytalne i podobne',
  'P8'],
 ['Pasywa',
  'B. Zobowiązania i rezerwy na zobowiązania',
  'I. Rezerwy na zobowiązania',
  '3. Pozostałe rezerwy',
  '3. Pozostałe rezerwy',
  'P9'],
 ['Pasywa',
  'B. Zobowiązania i rezerwy na zobowiązania',
  'II. Zobowiązania długoterminowe',
  '1. Wobec pozostałych jednostek',
  'a) kredyty i pożyczki',
  'P10'],
 ['Pasywa',
  'B. Zobowiązania i rezerwy na zobowiązania',
  'III. Zobowiązania krótkoterminowe',
  '1. Zobowiązania wobec jednostek powiązanych',
  'a) kredyty i pożyczki',
  'P11'],
 ['Pasywa',
  'B. Zobowiązania i rezerwy na zobowiązania',
  'III. Zobowiązania krótkoterminowe',
  '1. Zobowiązania wobec jednostek powiązanych',
  'b) tytułu dostaw i usług',
  'P12'],
 ['Pasywa',
  'B. Zobowiązania i rezerwy na zobowiązania',
  'III. Zobowiązania krótkoterminowe',
  '2. Zobowiązania wobec pozostałych jednostek',
  'a) kredyty i pożyczki',
  'P13'],
 ['Pasywa',
  'B. Zobowiązania i rezerwy na zobowiązania',
  'III. Zobowiązania krótkoterminowe',
  '2. Zobowiązania wobec pozostałych jednostek',
  'b) tytułu dostaw i usług',
  'P14'],
 ['Pasywa',
  'B. Zobowiązania i rezerwy na zobowiązania',
  'III. Zobowiązania krótkoterminowe',
  '2. Zobowiązania wobec pozostałych jednostek',
  'c) z tytułu podatków, ceł, etc.',
  'P15'],
 ['Pasywa',
  'B. Zobowiązania i rezerwy na zobowiązania',
  'III. Zobowiązania krótkoterminowe',
  '2. Zobowiązania wobec pozostałych jednostek',
  'd) z tytułu wynagrodzeń',
  'P16'],
 ['Pasywa',
  'B. Zobowiązania i rezerwy na zobowiązania',
  'III. Zobowiązania krótkoterminowe',
  '2. Zobowiązania wobec pozostałych jednostek',
  'e) inne',
  'P17'],
 ['Pasywa',
  'B. Zobowiązania i rezerwy na zobowiązania',
  'III. Zobowiązania krótkoterminowe',
  '3. Fundusze specjalne',
  '3. Fundusze specjalne',
  'P18'],
 ['Pasywa',
  'B. Zobowiązania i rezerwy na zobowiązania',
  'IV. Rozliczenia międzyokresowe',
  '1. Inne rozliczenia międzyokresowe',
  '1. Inne rozliczenia międzyokresowe',
  'P19'],
 ['Rachunek Wyników',
  'A. Przychody netto ze sprzedaży i zrównane z nimi',
  '1. Przychody netto ze sprzedaży produktów',
  '1. Przychody netto ze sprzedaży produktów',
  '1. Przychody netto ze sprzedaży produktów',
  'R1'],
 ['Rachunek Wyników',
  'A. Przychody netto ze sprzedaży i zrównane z nimi',
  '2.Przychody netto ze sprzedaży towarów i materiałów',
  '2.Przychody netto ze sprzedaży towarów i materiałów',
  '2.Przychody netto ze sprzedaży towarów i materiałów',
  'R2'],
 ['Rachunek Wyników',
  'A. Przychody netto ze sprzedaży i zrównane z nimi',
  '3. Koszt wytworzenia produktów na własne potrzeby',
  '3. Koszt wytworzenia produktów na własne potrzeby',
  '3. Koszt wytworzenia produktów na własne potrzeby',
  'R3'],
 ['Rachunek Wyników',
  'A. Przychody netto ze sprzedaży i zrównane z nimi',
  '4. Zmiana stanu produktów',
  '4. Zmiana stanu produktów',
  '4. Zmiana stanu produktów',
  'R4'],
 ['Rachunek Wyników',
  'B. Koszty działalności operacyjnej',
  '1. Amortyzacja',
  '1. Amortyzacja',
  '1. Amortyzacja',
  'R5'],
 ['Rachunek Wyników',
  'B. Koszty działalności operacyjnej',
  '2. Zużycie materiałów i energii',
  '2. Zużycie materiałów i energii',
  '2. Zużycie materiałów i energii',
  'R6'],
 ['Rachunek Wyników',
  'B. Koszty działalności operacyjnej',
  '3. Usługi obce',
  '3. Usługi obce',
  '3. Usługi obce',
  'R7'],
 ['Rachunek Wyników',
  'B. Koszty działalności operacyjnej',
  '4. Podatki i opłaty',
  '4. Podatki i opłaty',
  '4. Podatki i opłaty',
  'R8'],
 ['Rachunek Wyników',
  'B. Koszty działalności operacyjnej',
  '5. Wynagrodzenia',
  '5. Wynagrodzenia',
  '5. Wynagrodzenia',
  'R9'],
 ['Rachunek Wyników',
  'B. Koszty działalności operacyjnej',
  '6. Ubezpieczenia społeczne i inne świadczenia, w tym:',
  '6. Ubezpieczenia społeczne i inne świadczenia, w tym:',
  '6. Ubezpieczenia społeczne i inne świadczenia, w tym:',
  'R10'],
 ['Rachunek Wyników',
  'B. Koszty działalności operacyjnej',
  '7. Pozostałe koszty rodzajowe',
  '7. Pozostałe koszty rodzajowe',
  '7. Pozostałe koszty rodzajowe',
  'R11'],
 ['Rachunek Wyników',
  'B. Koszty działalności operacyjnej',
  '8. Wartość sprzedanych towarów i materiałów',
  '8. Wartość sprzedanych towarów i materiałów',
  '8. Wartość sprzedanych towarów i materiałów',
  'R12'],
 ['Rachunek Wyników',
  'C. Pozostałe przychody operacyjne',
  '1. Zysk z tytułu rozchodu niefinansowych aktywów trwałych',
  '1. Zysk z tytułu rozchodu niefinansowych aktywów trwałych',
  '1. Zysk z tytułu rozchodu niefinansowych aktywów trwałych',
  'R13'],
 ['Rachunek Wyników',
  'C. Pozostałe przychody operacyjne',
  '2. Inne przychody operacyjne',
  '2. Inne przychody operacyjne',
  '2. Inne przychody operacyjne',
  'R14'],
 ['Rachunek Wyników',
  'D. Pozostałe koszty operacyjne',
  '1. Inne koszty operacyjne',
  '1. Inne koszty operacyjne',
  '1. Inne koszty operacyjne',
  'R15'],
 ['Rachunek Wyników',
  'E. Przychody finansowe',
  '1. Odsetki',
  '1. Odsetki',
  '1. Odsetki',
  'R16'],
 ['Rachunek Wyników',
  'F. Koszty finansowe',
  '1. Odsetki',
  '1. Odsetki',
  '1. Odsetki',
  'R17'],
 ['Rachunek Wyników',
  'F. Koszty finansowe',
  '2. Inne',
  '2. Inne',
  '2. Inne',
  'R18'],
 ['Rachunek Wyników',
  'G. Podatek dochodowy',
  'G. Podatek dochodowy',
  'G. Podatek dochodowy',
  'G. Podatek dochodowy',
  'R19']]

t_mapa=pd.DataFrame(l_mapa,columns=['P0','P1','P2','P3','P4','ID'])

In [4]:
t_mapa.to_clipboard(decimal=',',excel=True,index=False)

In [9]:
# Buduje raport

t_zapisy['Kwota_SAL']=t_zapisy.apply(lambda x:x['Kwota_SAL'] if x['M']<=msc else 0,axis=1)
t_balance['Kwota_SAL']=t_balance.apply(lambda x:x['Kwota_SAL'] if x['M']<=msc else 0,axis=1)


t_okres=pd.DataFrame({'M':range(1,13)})
t_konta=t_balance[['Konto','Nazwa','ID']]
temp=t_balance[['Konto','ID','M','Kwota_DT','Kwota_CR','Kwota_SAL']].copy()

t_tech=t_mapa[['ID']].copy()
t_tech['Konto']='000-000'
t_tech['Nazwa']='Zapis techniczny'
t_tech=t_tech[['Konto','Nazwa','ID']]

t_konta=pd.concat([t_konta,t_tech],ignore_index=True)

t_konta=t_konta.drop_duplicates(['Konto','Nazwa','ID'])
t_konta['Konto_N']=t_konta['Konto']+ ' - '+t_konta['Nazwa']
t_konta=pd.merge(t_konta,t_okres,how='cross')
t_konta=pd.merge(t_konta,temp,how='left',on=['Konto','ID','M'])

t_wynik=t_balance[t_balance['ID'].str.startswith('R')].groupby(['M'],as_index=False)[['Kwota_DT','Kwota_CR','Kwota_SAL']].sum()
t_wynik['Konto']='000-000'
t_wynik['Nazwa']='Wynik finansowy'
t_wynik['Konto_N']='000-000 - Wynik finansowy'
t_wynik['ID']='P5'

t_konta=pd.concat([t_konta,t_wynik],ignore_index=True)

t_konta.fillna(0,inplace=True)

t_konta['Kwota_YTD'] = t_konta.groupby('Konto')['Kwota_SAL'].transform(pd.Series.cumsum)
t_konta['Kwota_YTD']=t_konta.apply(lambda x:-x['Kwota_YTD'] if x['ID'].startswith('A') else x['Kwota_YTD'],axis=1)
t_konta['Kwota_SAL']=t_konta.apply(lambda x:-x['Kwota_SAL'] if x['ID'].startswith('A') else x['Kwota_SAL'],axis=1)
t_konta=pd.merge(t_konta,t_mapa,how='left',on=['ID'])

In [10]:
t1=t_mapa[['P0']].drop_duplicates()

H='Analiza SF'

t_tabela=pd.pivot_table(t_konta,index=['P0'],values=['Kwota_SAL'],columns=['M'],aggfunc=[np.sum],fill_value=0,margins=True,margins_name='RAZEM').reset_index()
t_tabela=pd.DataFrame(t_tabela.values.tolist(),columns=[H,1,2,3,4,5,6,7,8,9,10,11,12,'RAZEM'])
t_tabela[H]=t_tabela[H].str.slice(0,50)
t_tabela.drop(t_tabela[t_tabela['RAZEM']==0].index,inplace=True)

t_tabela_fv=t_tabela.style.format(
    {1:'{0:,.2f}',2:'{0:,.2f}',3:'{0:,.2f}',4:'{0:,.2f}',5:'{0:,.2f}',6:'{0:,.2f}',7:'{0:,.2f}',8:'{0:,.2f}',9:'{0:,.2f}',10:'{0:,.2f}',11:'{0:,.2f}',12:'{0:,.2f}','RAZEM':'{0:,.2f}'}).hide(
        axis='index').set_properties(
            subset=[1,2,3,4,5,6,7,8,9,10,11,12,'RAZEM'], **{'width': '80px'}).set_properties(
                subset=[H], **{'width': '400px'},**{'text-align': 'left'})
display(t_tabela_fv)

#-------------------------------------------------

for index, row in t1.iterrows():
    p_0=row['P0']

    P0=p_0
    H=P0

    t_tabela=pd.pivot_table(t_konta[(
        t_konta['P0']==P0)
    ],index=['P1'],values=['Kwota_SAL'],columns=['M'],aggfunc=[np.sum],fill_value=0,margins=True,margins_name='RAZEM').reset_index()

    t_tabela=pd.DataFrame(t_tabela.values.tolist(),columns=[H,1,2,3,4,5,6,7,8,9,10,11,12,'RAZEM'])
    t_tabela[H]=t_tabela[H].str.slice(0,50)
    t_tabela.drop(t_tabela[t_tabela['RAZEM']==0].index,inplace=True)

    t_tabela_fv=t_tabela.style.format(
        {1:'{0:,.2f}',2:'{0:,.2f}',3:'{0:,.2f}',4:'{0:,.2f}',5:'{0:,.2f}',6:'{0:,.2f}',7:'{0:,.2f}',8:'{0:,.2f}',9:'{0:,.2f}',10:'{0:,.2f}',11:'{0:,.2f}',12:'{0:,.2f}','RAZEM':'{0:,.2f}'}).hide(
            axis='index').set_properties(
                subset=[1,2,3,4,5,6,7,8,9,10,11,12,'RAZEM'], **{'width': '80px'}).set_properties(
                    subset=[H], **{'width': '400px'},**{'text-align': 'left'})
    display(t_tabela_fv)

    t2=t_mapa[t_mapa['P0']==p_0]
    t2=t2[['P0','P1']].drop_duplicates()
    

#---------------------------------

    for index, row in t2.iterrows():

        p_0=row['P0']
        p_1=row['P1']

        P0=p_0
        P1=p_1
        H=P0+' '+P1

        t_tabela=pd.pivot_table(t_konta[(
            t_konta['P0']==P0)
            &(t_konta['P1']==P1)
        ],index=['P2'],values=['Kwota_SAL'],columns=['M'],aggfunc=[np.sum],fill_value=0,margins=True,margins_name='RAZEM').reset_index()

        t_tabela=pd.DataFrame(t_tabela.values.tolist(),columns=[H,1,2,3,4,5,6,7,8,9,10,11,12,'RAZEM'])
        t_tabela[H]=t_tabela[H].str.slice(0,50)
        t_tabela.drop(t_tabela[t_tabela['RAZEM']==0].index,inplace=True)

        t_tabela_fv=t_tabela.style.format(
            {1:'{0:,.2f}',2:'{0:,.2f}',3:'{0:,.2f}',4:'{0:,.2f}',5:'{0:,.2f}',6:'{0:,.2f}',7:'{0:,.2f}',8:'{0:,.2f}',9:'{0:,.2f}',10:'{0:,.2f}',11:'{0:,.2f}',12:'{0:,.2f}','RAZEM':'{0:,.2f}'}).hide(
                axis='index').set_properties(
                    subset=[1,2,3,4,5,6,7,8,9,10,11,12,'RAZEM'], **{'width': '80px'}).set_properties(
                        subset=[H], **{'width': '400px'},**{'text-align': 'left'})
        display(t_tabela_fv)

        t3=t_mapa[(t_mapa['P0']==p_0)&(t_mapa['P1']==p_1)]
        t3=t3[['P0','P1','P2']].drop_duplicates()

#---------------------------------------
        for index, row in t3.iterrows():
            p_0=row['P0']
            p_1=row['P1']
            p_2=row['P2']

            P0=p_0
            P1=p_1
            P2=p_2
            
            H=P0+' '+P1+' '+P2

            t_tabela=pd.pivot_table(t_konta[(
                t_konta['P0']==P0)
                &(t_konta['P1']==P1)
                &(t_konta['P2']==P2)
            ],index=['P3'],values=['Kwota_SAL'],columns=['M'],aggfunc=[np.sum],fill_value=0,margins=True,margins_name='RAZEM').reset_index()

            t_tabela=pd.DataFrame(t_tabela.values.tolist(),columns=[H,1,2,3,4,5,6,7,8,9,10,11,12,'RAZEM'])
            t_tabela[H]=t_tabela[H].str.slice(0,50)
            t_tabela.drop(t_tabela[t_tabela['RAZEM']==0].index,inplace=True)

            t_tabela_fv=t_tabela.style.format(
                {1:'{0:,.2f}',2:'{0:,.2f}',3:'{0:,.2f}',4:'{0:,.2f}',5:'{0:,.2f}',6:'{0:,.2f}',7:'{0:,.2f}',8:'{0:,.2f}',9:'{0:,.2f}',10:'{0:,.2f}',11:'{0:,.2f}',12:'{0:,.2f}','RAZEM':'{0:,.2f}'}).hide(
                    axis='index').set_properties(
                        subset=[1,2,3,4,5,6,7,8,9,10,11,12,'RAZEM'], **{'width': '80px'}).set_properties(
                            subset=[H], **{'width': '400px'},**{'text-align': 'left'})
            display(t_tabela_fv)

            t4=t_mapa[(t_mapa['P0']==p_0)&(t_mapa['P1']==p_1)&(t_mapa['P2']==p_2)]
            t4=t4[['P0','P1','P2','P3']].drop_duplicates()

            for index, row in t4.iterrows():
                p_0=row['P0']
                p_1=row['P1']
                p_2=row['P2']
                p_3=row['P3']

                P0=p_0
                P1=p_1
                P2=p_2
                P3=p_3
    

                H=P0+' '+P1+' '+P2+' '+P3

                t_tabela=pd.pivot_table(t_konta[(
                    t_konta['P0']==P0)
                    &(t_konta['P1']==P1)
                    &(t_konta['P2']==P2)
                    &(t_konta['P3']==P3)
                
                ],index=['P4'],values=['Kwota_SAL'],columns=['M'],aggfunc=[np.sum],fill_value=0,margins=True,margins_name='RAZEM').reset_index()

                t_tabela=pd.DataFrame(t_tabela.values.tolist(),columns=[H,1,2,3,4,5,6,7,8,9,10,11,12,'RAZEM'])
                t_tabela[H]=t_tabela[H].str.slice(0,50)
                t_tabela.drop(t_tabela[t_tabela['RAZEM']==0].index,inplace=True)

                t_tabela_fv=t_tabela.style.format(
                    {1:'{0:,.2f}',2:'{0:,.2f}',3:'{0:,.2f}',4:'{0:,.2f}',5:'{0:,.2f}',6:'{0:,.2f}',7:'{0:,.2f}',8:'{0:,.2f}',9:'{0:,.2f}',10:'{0:,.2f}',11:'{0:,.2f}',12:'{0:,.2f}','RAZEM':'{0:,.2f}'}).hide(
                        axis='index').set_properties(
                            subset=[1,2,3,4,5,6,7,8,9,10,11,12,'RAZEM'], **{'width': '80px'}).set_properties(
                                subset=[H], **{'width': '400px'},**{'text-align': 'left'})
                display(t_tabela_fv)

                t5=t_mapa[(t_mapa['P0']==p_0)&(t_mapa['P1']==p_1)&(t_mapa['P2']==p_2)&(t_mapa['P3']==p_3)]
                t5=t5[['P0','P1','P2','P3','P4']].drop_duplicates()

                for index, row in t5.iterrows():

                    P0=row['P0']
                    P1=row['P1']
                    P2=row['P2']
                    P3=row['P3']
                    P4=row['P4']

                    H=P0+' '+P1+' '+P2+' '+P3+' '+P4

                    t_tabela=pd.pivot_table(t_konta[(
                        t_konta['P0']==P0)
                        &(t_konta['P1']==P1)
                        &(t_konta['P2']==P2)
                        &(t_konta['P3']==P3)
                        &(t_konta['P4']==P4)
                    ],index=['Konto_N'],values=['Kwota_SAL'],columns=['M'],aggfunc=[np.sum],fill_value=0,margins=True,margins_name='RAZEM').reset_index()

                    t_tabela=pd.DataFrame(t_tabela.values.tolist(),columns=[H,1,2,3,4,5,6,7,8,9,10,11,12,'RAZEM'])
                    t_tabela[H]=t_tabela[H].str.slice(0,50)
                    t_tabela.drop(t_tabela[t_tabela['RAZEM']==0].index,inplace=True)


                    t_tabela_fv=t_tabela.style.format(
                        {1:'{0:,.2f}',2:'{0:,.2f}',3:'{0:,.2f}',4:'{0:,.2f}',5:'{0:,.2f}',6:'{0:,.2f}',7:'{0:,.2f}',8:'{0:,.2f}',9:'{0:,.2f}',10:'{0:,.2f}',11:'{0:,.2f}',12:'{0:,.2f}','RAZEM':'{0:,.2f}'}).hide(
                            axis='index').set_properties(
                                subset=[1,2,3,4,5,6,7,8,9,10,11,12,'RAZEM'], **{'width': '80px'}).set_properties(
                                    subset=[H], **{'width': '400px'},**{'text-align': 'left'})
                    display(t_tabela_fv)